"""
Thin wrapper that now delegates to the centralized plotting utilities in
`figures.py`. The original phase-diagram, margin, and time-series plots can
be regenerated by running this module, but the implementation lives in a
single shared place.
"""

from __future__ import annotations

from .figures import (
    plot_phase_diagrams_and_margins,
    plot_time_series_slices,
    plot_timescale_band,
)


def main() -> None:
    plot_timescale_band()
    plot_phase_diagrams_and_margins()
    plot_time_series_slices()


if __name__ == "__main__":
    main()
